object Form1: TForm1
  Left = 0
  Top = 0
  Caption = 'Form1'
  ClientHeight = 387
  ClientWidth = 606
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnResize = FormResize
  PixelsPerInch = 96
  TextHeight = 13
  object StelMap1: TStelMap
    Left = 0
    Top = 0
    Width = 606
    Height = 387
    Align = alClient
    Picture.Data = {07544269746D617000000000}
    CachePath = '.\Cache\'
    TypeMap = OpenStreetMap
    proxyport = 0
    ExplicitLeft = 67
    ExplicitTop = 37
    ExplicitWidth = 400
    ExplicitHeight = 200
  end
end
